import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useSettings } from '../SettingsContext';
import { WORD_CATEGORIES_KEYS } from '../../data/words';
import { CalibrationScreen } from './CalibrationScreen';
import '../../styles/components.css';
export function ConfigScreen({ onBack }) {
    const { settings, updateSettings } = useSettings();
    const [showCalibration, setShowCalibration] = useState(false);
    if (showCalibration) {
        return _jsx(CalibrationScreen, { onComplete: () => setShowCalibration(false) });
    }
    return (_jsxs("div", { className: "config-screen", children: [_jsx("h1", { children: "Configuraci\u00F3n" }), _jsxs("div", { className: "config-section", children: [_jsx("label", { htmlFor: "duration", children: "Duraci\u00F3n de la ronda (segundos)" }), _jsxs("div", { className: "input-group", children: [_jsx("input", { id: "duration", type: "range", min: "30", max: "180", step: "10", value: settings.duration, onChange: e => updateSettings({ duration: parseInt(e.target.value) }) }), _jsxs("span", { className: "value", children: [settings.duration, "s"] })] })] }), _jsxs("div", { className: "config-section", children: [_jsx("label", { htmlFor: "category", children: "Categor\u00EDa" }), _jsx("select", { id: "category", value: settings.category, onChange: e => updateSettings({ category: e.target.value }), children: WORD_CATEGORIES_KEYS.map(cat => (_jsx("option", { value: cat, children: cat.charAt(0).toUpperCase() + cat.slice(1) }, cat))) })] }), _jsxs("div", { className: "config-section", children: [_jsx("label", { htmlFor: "threshold", children: "Sensibilidad de inclinaci\u00F3n" }), _jsxs("div", { className: "input-group", children: [_jsx("input", { id: "threshold", type: "range", min: "15", max: "45", step: "5", value: settings.tiltThreshold, onChange: e => updateSettings({ tiltThreshold: parseInt(e.target.value) }) }), _jsxs("span", { className: "value", children: [settings.tiltThreshold, "\u00B0"] })] })] }), _jsx("div", { className: "config-section", children: _jsxs("label", { htmlFor: "mixCategories", children: [_jsx("input", { id: "mixCategories", type: "checkbox", checked: settings.mixCategories, onChange: e => updateSettings({ mixCategories: e.target.checked }) }), "Mezclar categor\u00EDas"] }) }), _jsx("div", { className: "config-section", children: _jsxs("label", { htmlFor: "soundEnabled", children: [_jsx("input", { id: "soundEnabled", type: "checkbox", checked: settings.soundEnabled, onChange: e => updateSettings({ soundEnabled: e.target.checked }) }), "Sonidos activados"] }) }), _jsx("div", { className: "config-section", children: _jsxs("label", { htmlFor: "vibrationEnabled", children: [_jsx("input", { id: "vibrationEnabled", type: "checkbox", checked: settings.vibrationEnabled, onChange: e => updateSettings({ vibrationEnabled: e.target.checked }) }), "Vibraci\u00F3n activada"] }) }), _jsx("button", { onClick: () => setShowCalibration(true), className: "btn btn-secondary", children: "Calibrar Sensores" }), _jsx("button", { onClick: onBack, className: "btn btn-primary", children: "Volver" })] }));
}
